language: python 
  - "2.7"
env:
  global:
    - secure: "APLNqVF0vbnUi0K8WRUHUgiw8wRGMxNQYkdcwZLR2ixGGh/5PZ3KY+7QcJgMR2Cc2hMM7zNXjTAD9QgTfqiwPs+98vRcXhIdQCE1OWA/29GkaDzvlL6SZ1nU7h2qLHCcjW8szSEr4vgAy8mQCsATgM+5PeOtE+VlLwA3nWS1GvV448bbboPv36rDiorxvCkmj7M6MxBA53BlwHEEK1DG+qbwXsst6Qj58oe53sXc29ZNd60yV2L103egnTCYb1aiHPhBEo2tdBykcdGwdZhGPIkpPo19VAmWkNnwI6i4cuXKyWJ4zEsoL4gMJRgskyKMRxlejEtJCNkggQIzEToAf5z8WhrZRKtBnjjlOtU4Loyjzh6VoDOb79tJDAqTn/NlooCRDixnQDigrdRrPQkEuurC2FyRbL6tI+ufJa1ibvWNz+2YeVteFYrmpc3VwXj6Yzr89p78UY4fdOaZfTlZKkRMlrGvWiXn9b856gHHW89T7ALsXqY1xrnJZi5XUD/lfsDI+mjqNbGJYxyM25Exf2lCdsejYMo1/HQi6Odavq49Dk4M76ou/yelf3rarOtHrwTUlGXQu/bR2JB6rYScMtxqt1ivcgpxgfHrO/Gij7GJ2Tn6eP/U3geh8a1Gl63Rl1JoWzoyE3eSdCqtRZYEURqZZN7D9fUMpyoKCHwqJmI="
  warnings_are_errors: false
install:
  - pip install --user -q -r requirements.txt
script:
  - sphinx-build -b html -d build/doctrees source build/html
after_success:
  - bash deploy.sh
